version: '3.7'
services:
  kuber-nest-pg:
    container_name: kuber-nest-pg
    image: postgres
    restart: "no"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  kuber-nest-redis:
    container_name: kuber-nest-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  kuber-nest-clickhouse:
    container_name: kuber-nest-clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"

    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

volumes:
  redis:
    driver: local
