apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-nest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-nest
  template:
    metadata:
      labels:
        app: kuber-nest
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: app
          image: {{ .Values.werf.image.app }}
          command: ["npm", "start"]
          ports:
            - containerPort: 3000
          env:
            - name: DEBUG
              value: "app:*"