apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-panel-svc
  labels:
    app: rabbitmq-panel
    tier: backend
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-panel-svc-port
      port: 15672
      targetPort: 15672
