apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: rabbitmq
    tier: backend
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-svc-port
      port: 5672
      targetPort: 5672